layout_spectrum: 1
color:
  saturation: 0.7223416
  brandStrength: 0.3746294
  lightness: 0.5300752
  rhythmicContrast: 1
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.9274973
name: Stefan L. Smith
