collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.9274973
color:
  saturation: 0.7223416
  brandStrength: 0.3746294
  lightness: 0.31203
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  rhythmicContrast: 1
layout_spectrum: 1
name: Stefan L. Smith
