favicon: null
name: Stefan L. Smith
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.4409237
  brandStrength: 0.3746294
  rhythmicContrast: 0.6868958
  brandColors:
    - '#222222'
    - '#8b8b8b'
    - '#b5b5b5'
    - '#686868'
    - '#3e3e3e'
  lightness: 0.3754028
typography_spectrum: 0.9274973
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
